### ISSUE TITLE
Antech "Related" tests

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api#230]
**Is your feature request related to a problem? Please describe.**

We need DMI to pass along Antech's "related to" data between two test results in a result set. Currently, DMI does not include this concept in its normalized payload. Our data team is starting to have problems due to the lack of this data. 

The most common example is a Culture and Sensitivity where the bacterial organism that has been cultured is "related to" sensitivity data for specific Antimicrobial components. 

E.g. - E. coli (cultured bacteria) has a value associated with Ampicillin (antibiotic). There may be more then one cultured organism so the report may hvae two values of Ampicillin. One is associated with the "E. coli (org 1)" and the second is associated with "Staph cocci (organism 2)."

**Describe the solution you'd like**

Because the "Code" value already is mapped to Antech's "Ext-ID" value, we could add "RelatedCode" that takes Antech's "Related-Ext-ID" value. At this time, no other providers do this, so that value would be null or the code absent if it wasn't specified.

**Describe alternatives you've considered**

**Additional context**

_The Antech data looks like this:_ 	
			<TestCode Ext-ID="4812"
			          Status="F"
			          Type="TMIC"
**_Related-Ext-ID="4912"_**>
<Name>Ampicillin</Name>
<Value>&lt;=0.25</Value>
<Units><![CDATA[ug/ml]]></Units>
<Range>0.25-0.5</Range>
<Comment><![CDATA[Ampicillin:  11 mg/kg SC q 12hrs]]></Comment>
</TestCode>
<TestCode Ext-ID="4912"
			          Status="F"
			          Type="TMICINT">
<Name>Ampicillin Int</Name>
<Value>S</Value>
<Units/>
<Range/>
</TestCode>

The "related-Ext-ID" serves as an indication that the TestCode for "Ampicillin" is directly related to the "Ampicillin Int" (i.e. the interpretation value).

**Comment by monsieurBelbo** [comment]
**Proposed solution**

Adding an `Observation.related` array property:
```yaml
title: Observation
type: object
properties:
  ...
  related:
    type: array
    description: |
      Related observations, e.g. derived from the same specimen.
    items:
      $ref: '../types/ObservationRelationship.yaml'
```

where `ObservationRelationship` is:
```yaml
title: ObservationRelationship
type: object
description: Resource related to this observation.
properties:
  type:
    type: string
    description: | 
      A code specifying the kind of relationship that exists with the target resource:
        - has-member: This observation is a group observation (e.g. a battery, a panel of tests, a set of vital sign measurements) that includes the target as a member of the group.
        - sequel-to: This observation follows the target observation (e.g. timed tests such as Glucose Tolerance Test).
        - replaces: This observation replaces a previous observation (i.e. a revised value). The target observation is now obsolete.
        - qualified-by: The value of the target observation qualifies (refines) the semantics of the source observation (e.g. a lipemia measure target from a plasma measure)
        - interfered-by: The value of the target observation interferes (degrades quality, or prevents valid observation) with the semantics of the source observation (e.g. a hemolysis measure target from a plasma potassium measure which has no value).
        - is-interpretation-of: The value of the target observation is an interpretation of this observation (e.g. low, high, normal).
    example: has-member
    enum:
      - has-member
      - sequel-to
      - replaces
      - qualified-by
      - interfered-by
      - is-interpretation-of
  target:
    type: string
    description: The target resource that belongs to the observation.
    example: 3025460e-7606-4643-a1ff-47c732e8ab20
required:
  - type
  - target
```
